<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>educational-center-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <!-- Required by "dotnet ef" because this is the startup project. -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EducationalCenter.Application\EducationalCenter.Application.csproj" />
    <ProjectReference Include="..\EducationalCenter.Infrastructure\EducationalCenter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
